# Generated by Django 4.2.1 on 2023-05-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
        ('game_platform', '0001_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='game_platform',
            field=models.ManyToManyField(blank=True, null=True, to='game_platform.gameplatformmodel'),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, to='genre.gamegenremodel'),
        ),
    ]
